### ISSUE TITLE
Build newer version?

### ISSUE THREAD

**Issue by maresb** [anthrotype/resvg-wheels#3]
Hey @anthrotype, it would be great to get the latest version of resvg on PyPI. Would you be open to another round of rebuilding/republishing?

Ideally it'd be great to get this running on a daily/weekly schedule to check for updates, but I'm guessing that there are some cobwebs to deal with since the last release.

**Comment by anthrotype** [comment]
I have just pushed the latest resvg v0.44.0

**Comment by maresb** [comment]
Awesome, thanks @anthrotype!!! Hope the :baby: is well!

**Comment by anthrotype** [comment]
yes thanks! getting chubbier every day :)
