### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by baseplate-admin** [anthrotype/resvg-wheels#4]
Hi it seems like this repository is not actively being worked on?

Is there any plans on adding more maintainers?

**Comment by anthrotype** [comment]
hey! well, kind of yes.. Sorry for the lack of updates here, we originally put this up to use it in https://github.com/googlefonts/nanoemoji color font compiler (to convert .svg files to .png for making bitmap color fonts) and it served its original purpose (which basically was demonstrating that vector color fonts are superior for most use cases).
We are interested in keeping it up to date of course, but I can't commit to do that on a more regular basis.
Are you volunteering?
What's your interest in this? I see from your Github activity you have another pyo3-based wrapper around resvg called resvg_py.

**Comment by baseplate-admin** [comment]
Hi thanks for getting back.

> I see from your Github activity you have another pyo3-based wrapper around resvg called resvg_py.

Yep, you have a pretty good eye, I developed that after i tried this module. The `resvg-cli` project is based on `0.22.0` version of `resvg` and didn't support my use case (i am doing a png generation from a svg from a `django` backend). Fun fact, `resvg-py` [version 0.0.1](https://github.com/baseplate-admin/resvg-py/tree/6aaa130e7e5f4639f0b878edaf0d4ce8252ec6e3) was based on this project's concept (but the approach is questionable)

> What's your interest in this, if I may ask?

There are use cases when i just want to try out resvg from the command line. If i dont have cargo/rust installed, i have to manually download a binary from github and then put it to path and deal with all sorts of nonsense. 

I planned to use this pip package to get `resvg` in a quick and easy way.

> We are interested in keeping it up to date of course, but I can't commit to do that on a more regular basis.

**Comment by anthrotype** [comment]
understood. Yeah, I'd like to have this more regularly updated but it's not at the top of my priorities at the moment (two weeks ago I had a :baby:). If you'd like to contribute patches to fix outstanding issues with CI mostly (making sure it works with the latest maturin and such) you're more than welcome. I could also add you as collaborator if need be.

**Comment by baseplate-admin** [comment]
> two weeks ago I had a 👶

Congratulations !!
